title:              Padma blogs
email:              padshak230@gmail.com
description:        Hi! I am beginner elixir developer. Going through hurdles and sharing how I overcame them.
author:             Padma Bajracharya
baseurl:            "/"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   PadmaBajzra
github_username:    padmaJS
facebook_username:  Bajra.padma
instagram_username:  
linkedin_username:

google_analytics:    G-BMXHJ2GS4X # out your google-analytics code

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
